name: Build Executable

on:
  push:
    tags: v*.*.*
  workflow_dispatch:

jobs:
  build_exe:
    name: Building Executable
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Install Dependencies
        run: |
          uv sync
          ./.venv/Scripts/pyinstaller.exe main.py --onefile --name ${{secrets.APP_NAME}} --noconsole
      - name: Create Realease
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/${{secrets.APP_NAME}}.exe
        
